services:
  frontend:
    container_name: frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile.prod
    ports:
      - "5173:5173"
    volumes:
      - build_folder:/frontend/dist
    networks:
      - teamM
    tty: true
    stdin_open: true

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsSL http://elasticsearch:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - teamM

  backend:
    container_name: backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    tty: true
    networks:
      - teamM

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - teamM

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - build_folder:/var/www/frontend
    depends_on:
      - frontend
      - backend
    networks:
      - teamM

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    platform: linux/amd64
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - teamM
    depends_on:
      - elasticsearch

volumes:
  esdata:
  build_folder:
networks:
  teamM:
    driver: bridge