services:
  fastapi:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      elasticsearch:
        condition: service_healthy
      postgresql:
        condition: service_started
      redis:
        condition: service_started
    restart:
      always
    env_file:
      - .env
    container_name: teamM
    tty: true
    networks:
      - teamM

  postgresql:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - teamM

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - teamM

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsSL http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - teamM

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - 80:80
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Nginx 설정 파일 마운트
#      - ./nginx/log:/var/log/nginx  # 로그 디렉토리 마운트
    depends_on:
      - fastapi
    networks:
      - teamM

volumes:
  postgres_data:
  esdata:

networks:
  teamM:
    driver: bridge
