global:
  scrape_interval: 15s #메트릭 수집 인터벌
  evaluation_interval: 15s #메트릭 평가 인터벌

scrape_configs:
  - job_name: 'prometheus-data'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'fastapi-data'
    static_configs:
      - targets: ['fastapi:8000']
  - job_name: 'redis-data'
    static_configs:
      - targets: ['redis-exporter:9121']
  - job_name: 'postgres-data'
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: 'elasticsearch-data'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
  - job_name: 'nginx-data'
    static_configs:
      - targets: ['nginx-exporter:9113']
  - job_name: 'node-data'
    static_configs:
      - targets: ['node_exporter:9100']