name: CD pipeline

on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Test SSH connection
      run: |
        ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo SSH connection successful"

    - name: Deploy to EC2
      run: |
        ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        if [ ! -d "/home/${{ secrets.EC2_USER }}/Summer-Bootcamp-2024/SML" ]; then
          git clone https://github.com/Summer-Bootcamp-2024/SML.git
        fi
        cd Summer-Bootcamp-2024/SML
        git pull origin main
        git submodule init Backend
        git submodule init Frontend
        git submodule update
        docker compose -f docker-compose.yml down
        docker compose -f docker-compose.yml up -d --build
        EOF
